### ISSUE TITLE
Add sound clips

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/biden-soundboard#1]
Add some sound clips to the repo. Try not to make duplicates. View the Readme for instructions.

**Comment by shubhdeep123** [comment]
hey @Pamblam if the voice is clear with little bit of background music will it be ok?

**Comment by Pamblam** [comment]
Please try to find clips without music. If someone put music over it it probably won't be hard to find the same clip without music.

**Comment by shubhdeep123** [comment]
https://nifty-bhaskara-ac7518.netlify.app/
This is link to the branch I have created for the repo with some styling does it looks good?

**Comment by Pamblam** [comment]
Some of the clips in that PR are cut short. Let's add these ones as well

 - [ ] "Poor kids just as talented as white kids"
 - [ ] "We choose truth over facts"
 - [ ] "Invasion of Hispanics"
 - [ ] "...my friend, been my friend, long time friend.."
 - [ ] "Dunkin donuts, slight indian accent"
 - [ ] "I'm joe biden's husband"
 - [ ] "...you ain't black"
 - [ ] "Lying dog faced pony soldier" - the one that's on there now is cut too soon
 - [ ] Biden challenging someone to a "push up contest"

Let's remove some of the less interesting clips and the clips that were cut too short as well.

**Comment by shubhdeep123** [comment]
@Pamblam  yeah sure and you please send the link to the video?

**Comment by Pamblam** [comment]
That wasn't directed specifically to you @shubhdeep123, just a general note to anyone. I want to keep this issue open as it's an ongoing thing. I don't have links to those videos you'd have to do a search.

**Comment by shubhdeep123** [comment]
> That wasn't directed specifically to you @shubhdeep123, just a general note to anyone. I want to keep this issue open as it's an ongoing thing. I don't have links to those videos you'd have to do a search.

Not a problem I ll do some research and create a PR soon.

**Comment by Pamblam** [comment]
Closing as Hacktoberfest has ended.
