### ISSUE TITLE
It's ugly - make it pretty

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/biden-soundboard#2]
Do whatever you want. It needs some styling. Just fix it.

**Comment by shubhdeep123** [comment]
I want to work on this

**Comment by Pamblam** [comment]
@shubhdeep123 Please do. If you’re doing it for Hacktoberfest you should wait until the first of the month to submit a PR or it won’t count.

**Comment by shubhdeep123** [comment]
> @shubhdeep123 Please do. If you’re doing it for Hacktoberfest you should wait until the first of the month to submit a PR or it won’t count.

Ok @Pamblam i'll make changes and will send PR on first of October

**Comment by shubhdeep123** [comment]
@Pamblam https://wizardly-borg-8c23a5.netlify.app/ here is the repo with some styling and more clips does it look appealing enough or you suggest some changes?

**Comment by Pamblam** [comment]
That looks great man! Submit your PR tomorrow and I'll pull it. Thank you.

**Comment by shubhdeep123** [comment]
@Pamblam I've sent a PR please Review it.
